# Workflow to update my recent GitHub activity in public repos

name: github-activity
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with my most recent GitHub activity in public repos
    steps:
      - name: Recent GitHub Activity - Profile Readme
      - uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updating recent public GitHub activity'
          MAX_LINES: 5
          DISABLED_EVENTS: ''
